
# ── MYSQL DATABASE ─────────────────────────────────────────

spring.datasource.url=${DATABASE_URL}

spring.datasource.username=${DATABASE_USERNAME}

spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ── HIKARI CONNECTION POOL ────────────────────────────────

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5


# ── JPA / HIBERNATE ───────────────────────────────────────

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

