

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=false


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

API_SECRET_KEY=${API_SECRET_KEY}

info.app.name=Aptech Student Portal
info.app.description=A full-stack Spring MVC application with JPA and Security
info.app.version=1.0.0
info.app.author=Maduka Johnpeter